"""users, calls, call legs

Revision ID: 5c102b6a6032
Revises:
Create Date: 2026-09-14 17:17:09.854136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c102b6a6032"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calls",
        sa.Column("room_code", sa.String(length=8), nullable=True),
        sa.Column(
            "pairing_mode",
            sa.Enum("ROOM_CODE", "DIAL_OUT", name="pairing_mode", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "BRIDGED",
                "COMPLETED",
                "FAILED",
                name="call_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("bridged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_reason", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_calls_room_code"), "calls", ["room_code"], unique=False)
    op.create_table(
        "users",
        sa.Column("phone_e164", sa.String(length=20), nullable=False),
        sa.Column(
            "primary_language",
            sa.Enum(
                "ENGLISH",
                "HINDI",
                "BENGALI",
                "TAMIL",
                "TELUGU",
                "GUJARATI",
                "KANNADA",
                "MALAYALAM",
                "MARATHI",
                "PUNJABI",
                "ODIA",
                name="language",
                native_enum=False,
                length=10,
            ),
            nullable=True,
        ),
        sa.Column(
            "secondary_language",
            sa.Enum(
                "ENGLISH",
                "HINDI",
                "BENGALI",
                "TAMIL",
                "TELUGU",
                "GUJARATI",
                "KANNADA",
                "MALAYALAM",
                "MARATHI",
                "PUNJABI",
                "ODIA",
                name="language",
                native_enum=False,
                length=10,
            ),
            nullable=True,
        ),
        sa.Column("last_call_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_phone_e164"), "users", ["phone_e164"], unique=True)
    op.create_table(
        "call_legs",
        sa.Column("call_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("provider_call_uuid", sa.String(length=64), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("INBOUND", "OUTBOUND", name="leg_direction", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("phone_e164", sa.String(length=20), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "IDENTIFY",
                "ASK_LANGUAGES",
                "MENU",
                "ROOM_CREATED",
                "WAIT_PEER",
                "ASK_ROOM_CODE",
                "ASK_NUMBER",
                "DIALING_PEER",
                "BRIDGED",
                "ENDED",
                name="leg_state",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "language_primary",
            sa.Enum(
                "ENGLISH",
                "HINDI",
                "BENGALI",
                "TAMIL",
                "TELUGU",
                "GUJARATI",
                "KANNADA",
                "MALAYALAM",
                "MARATHI",
                "PUNJABI",
                "ODIA",
                name="language",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "language_secondary",
            sa.Enum(
                "ENGLISH",
                "HINDI",
                "BENGALI",
                "TAMIL",
                "TELUGU",
                "GUJARATI",
                "KANNADA",
                "MALAYALAM",
                "MARATHI",
                "PUNJABI",
                "ODIA",
                name="language",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hangup_cause", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["call_id"], ["calls.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_call_legs_call_id"), "call_legs", ["call_id"], unique=False)
    op.create_index(op.f("ix_call_legs_phone_e164"), "call_legs", ["phone_e164"], unique=False)
    op.create_index(
        op.f("ix_call_legs_provider_call_uuid"), "call_legs", ["provider_call_uuid"], unique=True
    )
    op.create_index(op.f("ix_call_legs_user_id"), "call_legs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_call_legs_user_id"), table_name="call_legs")
    op.drop_index(op.f("ix_call_legs_provider_call_uuid"), table_name="call_legs")
    op.drop_index(op.f("ix_call_legs_phone_e164"), table_name="call_legs")
    op.drop_index(op.f("ix_call_legs_call_id"), table_name="call_legs")
    op.drop_table("call_legs")
    op.drop_index(op.f("ix_users_phone_e164"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_calls_room_code"), table_name="calls")
    op.drop_table("calls")
    # ### end Alembic commands ###
