"""Every line the IVR can speak, in English.

Translations live in `prompts/<language>.json`, generated by
`scripts/generate_prompts.py` and committed so they are reviewable and cost
nothing at call time.

**No placeholders.** A dynamic value - a room code, a phone number - is spoken
by appending it to a prompt, never by interpolating into translated text.
Machine translation reorders and mangles `{code}` markers, and a prompt that
says "Your room code is {code}" out loud is a broken call.
"""

from __future__ import annotations

from enum import StrEnum


class PromptKey(StrEnum):
    # First-time setup. Always spoken in English, because we do not yet know
    # what else the caller understands.
    ASK_PRIMARY_LANGUAGE = "ask_primary_language"
    ASK_SECONDARY_LANGUAGE = "ask_secondary_language"
    LANGUAGE_SAVED = "language_saved"
    LANGUAGE_NOT_UNDERSTOOD = "language_not_understood"

    # Main menu
    MAIN_MENU = "main_menu"
    INVALID_CHOICE = "invalid_choice"

    # Room pairing
    ROOM_CODE_IS = "room_code_is"
    WAITING_FOR_PEER = "waiting_for_peer"
    ASK_ROOM_CODE = "ask_room_code"
    ROOM_NOT_FOUND = "room_not_found"
    NOBODY_JOINED = "nobody_joined"

    # Dial out
    ASK_PHONE_NUMBER = "ask_phone_number"
    DIALING_NOW = "dialing_now"
    DIAL_FAILED = "dial_failed"

    # Bridge
    CONNECTED = "connected"
    PEER_HUNG_UP = "peer_hung_up"
    GOODBYE = "goodbye"


#: Source text. Phrased for speech, not for reading: short sentences, no
#: parentheses, digits spelled where a TTS voice would otherwise run them
#: together.
ENGLISH_PROMPTS: dict[PromptKey, str] = {
    PromptKey.ASK_PRIMARY_LANGUAGE: (
        "Welcome. Which language do you speak? Say the name of your language, "
        "or press 1 for Hindi, 2 for Tamil, 3 for Telugu, 4 for Kannada, "
        "5 for Malayalam, 6 for Marathi, 7 for Bengali, or 8 for English."
    ),
    PromptKey.ASK_SECONDARY_LANGUAGE: (
        "Which second language should be mixed in for technical words? "
        "Press 1 to keep English, or say the name of another language."
    ),
    PromptKey.LANGUAGE_SAVED: "Your language has been saved.",
    PromptKey.LANGUAGE_NOT_UNDERSTOOD: "Sorry, I did not understand that language.",
    PromptKey.MAIN_MENU: (
        "Press 1 to create a room. Press 2 to dial a number. "
        "Press 3 to join a room. Press 9 to change your language."
    ),
    PromptKey.INVALID_CHOICE: "Sorry, that is not a valid choice.",
    PromptKey.ROOM_CODE_IS: "Your room code is",
    PromptKey.WAITING_FOR_PEER: (
        "Please share this code with the other person and stay on the line."
    ),
    PromptKey.ASK_ROOM_CODE: "Please enter the room code, followed by the hash key.",
    PromptKey.ROOM_NOT_FOUND: "That room code was not found. Please try again.",
    PromptKey.NOBODY_JOINED: (
        "Nobody joined your room. Please call again when the other person is ready."
    ),
    PromptKey.ASK_PHONE_NUMBER: (
        "Please enter the phone number you want to call, followed by the hash key."
    ),
    PromptKey.DIALING_NOW: "Calling now. Please stay on the line.",
    PromptKey.DIAL_FAILED: "Sorry, that call could not be connected.",
    PromptKey.CONNECTED: "You are now connected. You can start speaking.",
    PromptKey.PEER_HUNG_UP: "The other person has hung up.",
    PromptKey.GOODBYE: "Goodbye.",
}


def speak_digits(digits: str) -> str:
    """Space out digits so a TTS voice reads 1282 as four numbers, not one.

    Without this a room code is spoken as "one thousand two hundred and
    eighty-two", which nobody can write down or repeat back.
    """
    return " ".join(digits)
